### ISSUE TITLE
Pre-trained models + configs are not accessible

### ISSUE THREAD

**Issue by FutureAILab** [LARC-CMU-SMU/FoodSeg103-Benchmark-v1#15]
Hi there,

Could anyone please check the link of pre-trained models & configs?

**Comment by XiongweiWu** [comment]
@FutureAILab Hi, please download the models from the link above (We have finished the course so the models are available again. Please download the pre-trained models from the **link**.) the table.

**Comment by FutureAILab** [comment]
@XiongweiWu

It looks like this on our side when trying to download (e.g., link: https://drive.google.com/drive/folders/1E5fZga8h65dNZCX1m8zywvB8MwrleFNg?usp=sharing (Swin-S)).
Could you please check again? Thank you for your support.

<img width="756" alt="Screenshot 2021-12-15 at 13 40 45" src="https://user-images.githubusercontent.com/78098789/146188328-0f1ba28c-d936-424e-9b18-cbab876d114f.png">

**Comment by XiongweiWu** [comment]
@FutureAILab Try this link (https://smu-my.sharepoint.com/:u:/g/personal/xwwu_smu_edu_sg/EWBcCC3QrO9LthKX66QCzyoBhFU7PHXKcHhh1lgIC98uKw?e=bHT7vM) which is placed above the table. Since I blocked the download link for 3 months, now I put all the models together.

**Comment by FutureAILab** [comment]
@XiongweiWu thank you, it works.
