### ISSUE TITLE
The link of the model/config in the readme.md seem to be dead.

### ISSUE THREAD

**Issue by KombangkoeDias** [LARC-CMU-SMU/FoodSeg103-Benchmark-v1#17]
I am trying to replicate the results on foodseg103 with SeTR-MLA(ViT-16/B). The [link](https://drive.google.com/drive/folders/17Ht1HQDaBJmS0FXaXGjHk0VQNhAJxrlF?usp=sharing) provided in readme.md leads to a 404 error page of google drive, please fix this.
Thanks

**Comment by XiongweiWu** [comment]
@KombangkoeDias Hi, since we blocked url of the models before, and I put all the models in this link: https://smu-my.sharepoint.com/:u:/g/personal/xwwu_smu_edu_sg/EWBcCC3QrO9LthKX66QCzyoBhFU7PHXKcHhh1lgIC98uKw?e=bHT7vM , and you can find the SeTR-MLA here.
