### ISSUE TITLE
Can't download config files

### ISSUE THREAD

**Issue by mccaly** [LARC-CMU-SMU/FoodSeg103-Benchmark-v1#25]
The link to the 'Model + Config' leads to a 404.

Can you fix and / or share the configuration files?

**Comment by XiongweiWu** [comment]
> The link to the 'Model + Config' leads to a 404.
> 
> Can you fix and / or share the configuration files?

https://smu-my.sharepoint.com/:u:/g/personal/xwwu_smu_edu_sg/EWBcCC3QrO9LthKX66QCzyoBhFU7PHXKcHhh1lgIC98uKw?e=bHT7vM

**Comment by mccaly** [comment]
Thanks. 

Do you have any config.json files you can share?
